name : DonationBroadcast
version: 1.0
main: me.Marni.donationbroadcast.DonationBroadcast
author: Marni
description: This plugin broadcasts donations!

commands:
     DBroadcast:
         usage: /<command>
         description: Broadcasts a test command!